export const TODO_ADD_SUCCESS = "TODO_ADD_SUCCESS"
export const TODO_ADD_FAIL = "TODO_ADD_FAIL"

export const TODO_GET_SUCCESS = "TODO_GET_SUCCESS"
export const TODO_GET_FAIL = "TODO_GET_FAIL"

export const TODO_UPDATE_SUCCESS = "TODO_UPDATE_SUCCESS"
export const TODO_UPDATE_FAIL = "TODO_UPDATE_FAIL"

export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS"
export const TODO_DELETE_FAIL = "TODO_DELETE_FAIL"